### ISSUE TITLE
Can you give some connection pool cases of MySQL, Redis and other services

### ISSUE THREAD

**Issue by leeyisoft** [okeuday/varpool#2]

**Comment by okeuday** [comment]
@leeyisoft Hi!
I created this Erlang application because I believe it is the best approach for providing a connection pool in a [CloudI](https://github.com/CloudI/CloudI) service.  However, I haven't needed to add it to any CloudI services yet because I haven't yet had any performance problems that would require it.  If a CloudI service isn't using any process pool, the service can always have its number of processes increased to handle more load and that can help keep the CloudI service logic simpler.

So, using a process pool inside a CloudI service could be used for situations with read-only connections/operations and other decisions based on the content of a request.  However, it still would likely be beneficial to handle that with CloudI service name patterns being different for different routing to the separate CloudI service processes (to split the throughput), so it may be hard to justify needing any process pool inside a CloudI service (i.e., the CloudI service only would need configuration arguments for the variation in its initialization).
